/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  theme: {
    extend: {
      fontFamily: {
        display: ['Outfit', 'system-ui', 'sans-serif'],
        sans: ['Manrope', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      colors: {
        bg: '#070A12',
        bg2: '#0B1020',
        bg3: '#05070D',
        ink: '#F8FAFC',
        muted: 'rgba(248, 250, 252, 0.62)',
        glass: 'rgba(255, 255, 255, 0.06)',
        'glass-strong': 'rgba(255, 255, 255, 0.10)',
        'glass-border': 'rgba(255, 255, 255, 0.12)',
        amber: { DEFAULT: '#F59E0B', soft: '#FCD34D', deep: '#B45309' },
        violet: { DEFAULT: '#7C3AED', soft: '#A78BFA', deep: '#5B21B6' },
        emerald: { DEFAULT: '#10B981', soft: '#6EE7B7' },
        rose: { DEFAULT: '#F43F5E', soft: '#FDA4AF' },
        // legacy aliases preserved for compatibility (mapped to dark theme accents)
        cream: '#070A12',
        lemon: '#F59E0B',
        lilac: '#7C3AED',
        mint: '#10B981',
        bubblegum: '#EC4899',
        // shadcn tokens
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      boxShadow: {
        'glow-amber': '0 0 0 1px rgba(245,158,11,.35), 0 8px 30px -8px rgba(245,158,11,.45)',
        'glow-violet': '0 0 0 1px rgba(124,58,237,.40), 0 8px 30px -8px rgba(124,58,237,.55)',
        'soft': '0 12px 40px -8px rgba(0,0,0,.45), 0 1px 0 0 rgba(255,255,255,.04) inset',
        'inner-glow': 'inset 0 1px 0 0 rgba(255,255,255,.08)',
      },
      backgroundImage: {
        'page-grad': "radial-gradient(circle at 12% 0%, rgba(124, 58, 237, 0.20), transparent 32%), radial-gradient(circle at 88% 0%, rgba(245, 158, 11, 0.16), transparent 30%), linear-gradient(180deg, #070A12 0%, #0B1020 50%, #05070D 100%)",
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        marquee: { '0%': { transform: 'translateX(0%)' }, '100%': { transform: 'translateX(-50%)' } },
        'fade-up': { '0%': { opacity: '0', transform: 'translateY(12px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        'pop-in': { '0%': { opacity: '0', transform: 'scale(0.92)' }, '100%': { opacity: '1', transform: 'scale(1)' } },
        'orb': { '0%, 100%': { transform: 'translate(0, 0) scale(1)' }, '50%': { transform: 'translate(20px, -10px) scale(1.06)' } },
        'sparkle': { '0%, 100%': { opacity: '.6', transform: 'scale(1)' }, '50%': { opacity: '1', transform: 'scale(1.12)' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'marquee': 'marquee 28s linear infinite',
        'fade-up': 'fade-up 0.5s ease-out both',
        'pop-in': 'pop-in 0.35s ease-out both',
        'orb': 'orb 14s ease-in-out infinite',
        'sparkle': 'sparkle 1.6s ease-in-out infinite',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
