"""Seeded debate rooms for AI Debate Rooms launch."""

DEBATES = [
    {
        "slug": "ai-creativity",
        "title": "Is AI creativity real creativity?",
        "description": "When an AI generates a poem, song, or design — is that genuine creative expression, or sophisticated imitation?",
        "category": "tech",
        "side_a_label": "It's real creativity",
        "side_b_label": "It's just imitation",
        "is_featured": True,
    },
    {
        "slug": "ai-clones-vs-influencers",
        "title": "Should AI clones replace influencers?",
        "description": "AI clones can stream, post, and chat 24/7. Are we ready to follow synthetic humans, or is something essential lost?",
        "category": "culture",
        "side_a_label": "Yes — clones win",
        "side_b_label": "No — humans matter",
        "is_featured": True,
    },
    {
        "slug": "voice-vs-text",
        "title": "Are voice messages better than text messages?",
        "description": "Voice notes feel intimate but waste time. Text is efficient but cold. Which medium actually serves communication?",
        "category": "lifestyle",
        "side_a_label": "Voice is better",
        "side_b_label": "Text is better",
        "is_featured": False,
    },
    {
        "slug": "dating-with-ai",
        "title": "Is dating easier or harder with AI?",
        "description": "AI helps draft messages, generate openers, even simulate conversations. Does it improve dating or hollow it out?",
        "category": "relationships",
        "side_a_label": "Easier with AI",
        "side_b_label": "Harder with AI",
        "is_featured": True,
    },
    {
        "slug": "ai-homework",
        "title": "Should students use AI for homework?",
        "description": "Calculators were once banned too. Is AI a learning amplifier or an erosion of thinking itself?",
        "category": "education",
        "side_a_label": "Yes — let them",
        "side_b_label": "No — ban it",
        "is_featured": False,
    },
    {
        "slug": "remote-vs-office",
        "title": "Is remote work better than office work?",
        "description": "Remote gives autonomy. Office builds culture. Which model produces better work, lives, and companies?",
        "category": "work",
        "side_a_label": "Remote wins",
        "side_b_label": "Office wins",
        "is_featured": False,
    },
    {
        "slug": "ai-friends",
        "title": "Are AI friends dangerous or helpful?",
        "description": "Millions are forming real bonds with AI companions. Coping mechanism or substitute for human connection?",
        "category": "mental-health",
        "side_a_label": "Helpful",
        "side_b_label": "Dangerous",
        "is_featured": True,
    },
    {
        "slug": "hide-likes",
        "title": "Should social media hide likes?",
        "description": "Public like counts drive validation loops and anxiety. Would hiding them improve mental health or just hide the signal?",
        "category": "social",
        "side_a_label": "Hide them",
        "side_b_label": "Keep them",
        "is_featured": False,
    },
]
